--INSERT INTO tbl_exercise (id_exercise, name_exercise, machine_number, muscle_group, video_uri) VALUES (1, 'Cadeira extensora', 15, 'Quadriceps', 'wwww.google.com');
--INSERT INTO tbl_exercise (id_exercise, name_exercise, machine_number, muscle_group, video_uri) VALUES (2, 'Pulley Costas', 16, 'Dorsais', 'wwww.google.com');
--INSERT INTO tbl_exercise (id_exercise, name_exercise, machine_number, muscle_group, video_uri) VALUES (3, 'Cadeira adutora', 03, 'Adutores', 'wwww.google.com');
--INSERT INTO tbl_exercise (id_exercise, name_exercise, machine_number, muscle_group, video_uri) VALUES (4, 'Cadeira flexora', 4, 'Isquiotibiais', 'wwww.google.com');
--INSERT INTO tbl_exercise (id_exercise, name_exercise, machine_number, muscle_group, video_uri) VALUES (5, 'Rosca simultãnea', 5, 'Bíceps', 'wwww.google.com');
--INSERT INTO tbl_exercise (id_exercise, name_exercise, machine_number, muscle_group, video_uri) VALUES (6, 'Triceps no cross', 27, 'Tríceps', 'wwww.google.com');
--
--INSERT INTO tbl_training (id_training, name_training, total_training, dt_concluded, status) VALUES (1, 'teste', 5, '2021-11-20T03:00:00Z', 'CONCLUDED')
--
--
--INSERT INTO tbl_exerciseitem (id_sequence, series_number, measurement_type, rest, concluded, quantity_number, note, tbl_training_id_training, tbl_exercise_id_exercise) VALUES (1, 4, 10, 30, 1, 7, 'Teste', 1,1)
--INSERT INTO tbl_exerciseitem (id_sequence, series_number, measurement_type, rest, concluded, quantity_number) VALUES (2, 5, 8, 45, 3, 5)
--INSERT INTO tbl_exerciseitem (id_sequence, series_number, measurement_type, rest, concluded, quantity_number) VALUES (3, 6, 12, 1, 6, 7)
--INSERT INTO tbl_exerciseitem (id_sequence, series_number, measurement_type, rest, concluded, quantity_number) VALUES (4, 6, 12, 1, 6, 7)
--INSERT INTO tbl_exerciseitem (id_sequence, series_number, measurement_type, rest, concluded, quantity_number) VALUES (5, 6, 12, 1, 6, 7)
